const mongoose = require("mongoose");

// ============================================================
// PAYMENT SCHEMA
// DEMO PAYMENT SYSTEM
// ============================================================

const paymentSchema = new mongoose.Schema(
  {
    // ============================================================
    // DONOR
    // ============================================================

    donor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // ============================================================
    // NGO RECEIVING THE PAYMENT
    // ============================================================

    ngo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // ============================================================
    // PAYMENT AMOUNT
    // ============================================================

    amount: {
      type: Number,
      required: true,
      min: 1,
    },

    // ============================================================
    // PAYMENT METHOD
    // ============================================================

    paymentMethod: {
      type: String,
      enum: [
        "upi",
        "bank_transfer",
        "card",
      ],
      required: true,
    },

    // ============================================================
    // DEMO TRANSACTION ID
    //
    // This will be generated by the backend.
    //
    // Example:
    // DEMO-UPI-1755701234567
    // DEMO-CARD-1755701234567
    // DEMO-BANK-1755701234567
    // ============================================================

    transactionId: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },

    // ============================================================
    // PAYMENT STATUS
    // ============================================================

    status: {
      type: String,
      enum: [
        "pending",
        "successful",
        "failed",
        "cancelled",
      ],
      default: "successful",
    },

    // ============================================================
    // PAYMENT TIME
    // ============================================================

    paidAt: {
      type: Date,
      default: Date.now,
    },
  },
  {
    timestamps: true,
  }
);

// ============================================================
// EXPORT MODEL
// ============================================================

module.exports = mongoose.model(
  "Payment",
  paymentSchema
);